### ISSUE TITLE
ERROR TypeError: this.onTouched is not a function.

### ISSUE THREAD

**Issue by NirArgil** [dineeek/ngx-numeric-range-form-field#3] opened 2022-06-07 11:28 UTC
Hi dineeek,
When i press the input field, start and end, and then leave it, I get this error.

Can you fix this please OR explain what should i do to fix it?

![image](https://user-images.githubusercontent.com/61774277/172368020-47c1d582-682e-4b1e-acaf-c81f36a7a804.png)

**Comment by dineeek** [comment] 2022-06-07 16:15
Hi NirArgil,

the problem is in the library and it is fixed in version 2.1.0. (npm i ngx-numeric-range-form-field@2.1.0) 
Please try it out and contact me if the error is still appearing.

Thanks!

**Comment by NirArgil** [comment] 2022-06-07 16:24
Now it is working without the Error.
Thank you sir.

**Closed as completed** 2022-06-07 17:50 UTC
